# Generated by Django 6.0.1 on 2026-02-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1-sinf'), ('2', '2-sinf'), ('3', '3-sinf'), ('4', '4-sinf'), ('5', '5-sinf'), ('6', '6-sinf'), ('7', '7-sinf'), ('8', '8-sinf'), ('9', '9-sinf'), ('10', '10-sinf'), ('11', '11-sinf')], max_length=10, null=True),
        ),
    ]
